### ISSUE TITLE
POST has to be explicitly defined using CURLOPT_CUSTOMREQUEST

### ISSUE THREAD

**Issue by asaeles** [incarnate/curl-to-php#14]
I tried running two consecutive PHP cURL outputs with two to the same URL, first one is set to OPTIONS:

> curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "OPTIONS");

Second one is supposed to be POST but only the CURLOPT_POST was set:

> curl_setopt($ch, CURLOPT_POST, 1);

But after running the PHP script the second -supposedly- "POST" request kept returning empty result for no particular reason, but after enabling the verbose flag on cURL I discovered that the second request was still set to OPTIONS, so I had to add:

> curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");

**Comment by asaeles** [comment]
Similar problem happened when a GET command succeeded a POST command, I had to add this line to the GET command disable the cURL option from the previous command:

> curl_setopt($ch, CURLOPT_POST, false);

**Comment by incarnate** [comment]
Hi @asaeles, 
Thanks for raising the issue, sorry to be slow to look at this one.

The issue seems to be in reusing a curl object for multiple requests. There isn't much this tool can do to help with that without setting almost every flag to its default value, which is a bit beyond what this is for.

I'll close this off, but if you've any further suggestions please post.
